### ISSUE TITLE
Improve about section

### ISSUE THREAD

**Issue by casassg** [HackCU/HackCU#29]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

Let's improve the about text. I feel like we can do better at encouraging students from all backgrounds to apply. An example for this would be https://2018.hackatbrown.org/#section2-about which has a similar goal than ours. Welcome people from all backgrounds on a weekend for learning and experimenting with technology.

Proposal:

>HackCU is all about learning, about improving yourself. Spend a weekend with us at the University of Colorado Boulder. We encourage students to take a step out of their comfort zone, to go beyond. Make HackCU your event by experimenting with a new platform, API, or that idea that’s always been in the back of your mind! We will provide the space and the resources for you to express your creativity, ingenuity, and determination to create anything you want to. Whether you’re building your first website, dabbling in Photoshop, or hacking with an Oculus Rift, HackCU is for individuals of all backgrounds and experiences. Join us!

**Comment by jessiemblack** [comment]
Love it! I say go for it.
