### ISSUE TITLE
New about proposal

### ISSUE THREAD

**Issue by casassg** [HackCU/HackCU#39]
## Text proposal

> To be inspired, driven, or motivated. To find what you always wanted, to finally dedicate your time and focus on a project or an idea you always wanted to start. To meet new people, and think aloud with them. To find that someone who understands your shares your vision, and wants to be part of it to start making it real. Come to HackCU.
>
> HackCU is all about learning, about improving yourself. Spend a weekend with us at the University of Colorado Boulder. We encourage you to take a step out of your comfort zone, to go beyond. Make HackCU your event by experimenting with a new platform, API, or that idea that’s always been in the back of your mind! We will provide the space and the resources for you to express your creativity, ingenuity, and determination to create anything you want to. Whether you’re building your first website, dabbling in Photoshop, or hacking with an Oculus Rift, HackCU is for individuals of all backgrounds and experiences. Join us!

Submitted by a friend of mine as a feedback from the current one

**Comment by elliotwhitehead** [comment]
I feel like @carlcortright accomplished the goal of this with his recent about us update? 

Thoughts? 

cc @casassg

**Comment by casassg** [comment]
Agree
