### ISSUE TITLE
DNS is messed up

### ISSUE THREAD

**Issue by casassg** [HackCU/HackCU#77]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG

## What happened

DNS seems to be broken (again).

```
# nslookup hackcu.org

Non-authoritative answer:
Name:	hackcu.org
Address: 185.199.109.153
Name:	hackcu.org
Address: 185.199.111.153
Name:	hackcu.org
Address: 54.149.182.89
Name:	hackcu.org
Address: 185.199.108.153
Name:	hackcu.org
Address: 185.199.110.153
```

Seems like someone added the a CNAME to the old AWS server.

Also, my.hackcu.org DNS entry seems to be missing again, not sure if inteded.

## What you expected to happen

Hackcu.org actually load.

## How to reproduce it (as minimally and precisely as possible)

Open hackcu.org

## Anything else we need to know?

Nope

**Comment by peasant98** [comment]
Currently my.hackcu.org is brought down until registration opens up. 

The AWS IP shouldn't show up anymore for `nslookup hackcu.org` as well.

**Comment by casassg** [comment]
perfect
